# requests to be tested with REST Client

# GET all users
GET http://localhost:5000/api/users

###

# GET an existing user
GET http://localhost:5000/api/users/1

###

# GET an non existing user
GET http://localhost:5000/api/users/0

###

# POST a new user
POST http://localhost:5000/api/users
Content-Type: application/json

{
    "email": "me2@mail.com",
    "password": "123456"
}

###

# PUT an existing user
PUT http://localhost:5000/api/users/1
Content-Type: application/json

{
    "email": "me3@mail.com",
    "password": "654321"
}

###

# PUT an non existing user
PUT http://localhost:5000/api/users/0
Content-Type: application/json

{
    "email": "me3@mail.com",
    "password": "654321"
}

###

# PUT an existing user
DELETE http://localhost:5000/api/users/1
